### ISSUE TITLE
Can't run example from the README

### ISSUE THREAD

**Issue by inpefess** [nokaut/wsknn#29]
The README example starts with

```python
ITEMS = 'demo-data/items.pkl'
SESSIONS = 'demo-data/sessions.pkl'
```

what are these `pkl` files, how can a potential new user find or generate them? There is a `demo-data` folder, but not in the root, and there are no `items.pkl` or `sessions.pkl` files anywhere in the repository.

**Comment by SimonMolinsky** [comment]
Hi @inpefess 

Thanks for pointing this out! I have created demo examples here: https://github.com/nokaut/wsknn/tree/main/demo-notebooks, and I see that `README` content differs from those. I will update `README` accordingly to use *recsys* data.
