### ISSUE TITLE
General question on input data format

### ISSUE THREAD

**Issue by inpefess** [nokaut/wsknn#36]
The `fit` method expects two maps (sessions2items and items2sessions), but we can always construct the second argument from the first, can't we? What is the purpose of such data duplication? Why can't it be part of the `fit` method (and as a consequence, why does one have to store such datasets)? It might be worth mentioning in the JOSS paper (there is only the first argument now mentioned in the draft).

**Comment by SimonMolinsky** [comment]
Ok, it's done. Now user can store only session-items mapping (or raw session events).
